name: heart_disease_dashboard
dependencies:
  - python=3.10  # Or your Python version
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - flask
  - fastapi
  - jupyter
  - shap
  - lime
  - streamlit
  - altair
  - bokeh
  - tensorflow
  - xgboost
  - joblib
  - plotly
  - plotly-express